-- generell stellt sich die Frage anhand welche Kriterien wir die Größe von versch. datatypes wählen
-- welche werte/pk müssen explizit als unique deklariert werden?
-- constraints und so fehlen (on cascade, not null, unique) 
-- wie generaten wir IDs? auto_increment oder? 
-- FK mitwirkende noch überall einfügen 
-- datatypes überprüfen, ich habe varchar bei unsicherheit benutzt
-- 'Autor',  book  'Künstler', cd 'Schauspieler', dvd 'Regisseur', dvd 'Filmemacher', dvd , 'publisher' buch eigene Relation, 'Label', cd 
--ck_...   = CHECK Constraint
--pk_...   = Primary Key
--fk_...   = Foreign Key
--uq_...   = Unique Constraint
--idx_...  = Index

CREATE TYPE product_type_enum AS ENUM ('book','music_cd','dvd'); 
CREATE TYPE contributor_rolle AS ENUM ('Autor/in' , 'Künstler/in', 'Schauspieler/in', 'Filmemacher/in', 'Regisseur/in') ; 

CREATE TABLE product(
    product_id      VARCHAR(50) NOT NULL, 
    title           VARCHAR(255) NOT NULL,
    product_type product_type_enum NOT NULL,
    salesrank       INTEGER,
    picture         VARCHAR(1000),
    -- rating wird aus reviews berechnet, daher kein Attribut in der Produkt-Tabelle
    
    CONSTRAINT pk_product 
        PRIMARY KEY (product_id), 

    CONSTRAINT ck_product_salesrank 
        CHECK (salesrank IS NULL OR salesrank > 0)
);  

CREATE TABLE category(
    category_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_name VARCHAR(200) NOT NULL,
    parent_category_id INTEGER, --wir haben dann quasi eine tabelle mit category_id und zugehörigen parent_id, der entweder eine zahl sein kann (die wiederum auf eine kategorie zeigt) oder eben NULL weil die Kategorie keine Oberkategorie hat, weil sie selber eine Oberkategorie ist. 

    CONSTRAINT pk_category
        PRIMARY KEY (category_id),

    CONSTRAINT fk_category_parent
        FOREIGN KEY (parent_category_id)
        REFERENCES category (category_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

CREATE TABLE product_category (
    product_id  VARCHAR(50) NOT NULL,
    category_id INTEGER NOT NULL,

    CONSTRAINT pk_product_category
        PRIMARY KEY (product_id, category_id),

    CONSTRAINT fk_product_category_product
        FOREIGN KEY (product_id)
        REFERENCES product (product_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_product_category_category
        FOREIGN KEY (category_id)
        REFERENCES category (category_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE similar_products (
    product_id         VARCHAR(50) NOT NULL,
    similar_product_id VARCHAR(50) NOT NULL,

    CONSTRAINT pk_similar_products
        PRIMARY KEY (product_id, similar_product_id),
    
    CONSTRAINT fk_similar_origin
        FOREIGN KEY (product_id) REFERENCES product (product_id) ON DELETE CASCADE,
        
    CONSTRAINT fk_similar_target
        FOREIGN KEY (similar_product_id) REFERENCES product (product_id) ON DELETE CASCADE,

    CONSTRAINT ck_not_self_similar
        CHECK (product_id != similar_product_id)
);

--Mitwirkinde
CREATE TABLE contributor(
    contributor_id      INTEGER GENERATED BY DEFAULT AS IDENTITY  NOT NULL, 
    contributor_name    VARCHAR(200) NOT NULL,

    CONSTRAINT pk_contributor 
        PRIMARY KEY (contributor_id),

    CONSTRAINT ck_contributor_id 
        CHECK (contributor_id > 0)
);

--Mitwirkende_produkt
CREATE TABLE contributor_product(
    product_id VARCHAR(50) NOT NULL,
    contributor_id INTEGER NOT NULL,
    rolle contributor_rolle NOT NULL,

    CONSTRAINT pk_contributor_product
        PRIMARY KEY (product_id, contributor_id, rolle),

    CONSTRAINT fk_contributor_product_product
        FOREIGN KEY (product_id)
        REFERENCES product (product_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_contributor_product_contributor
        FOREIGN KEY (contributor_id)
        REFERENCES contributor (contributor_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
); 

--Verlag
CREATE TABLE publisher(
    publisher_id INTEGER GENERATED BY DEFAULT AS IDENTITY,   --oder ist in den data schon publishers vorgegeben?
    publisher_name VARCHAR(200) NOT NULL,
    CONSTRAINT pk_publisher 
        PRIMARY KEY (publisher_id)
); 

CREATE TABLE book(
    product_id VARCHAR(50) NOT NULL,
    isbn VARCHAR(20) UNIQUE,  --VARCHAR weil ISBN zeichen/buchstabe X enthalten können 
    pages INTEGER CHECK ( pages IS NULL OR pages>0), -- Seitenzahl kann auch unbekannt sein, daher NULL 
    publication_date DATE, --kein Check, da auch zukünftige Buchveröffentlichungen angezeigt werden können 
    publisher_id INTEGER,

    CONSTRAINT pk_book
        PRIMARY KEY (product_id),

    CONSTRAINT fk_book_product
        FOREIGN KEY (product_id)
        REFERENCES product (product_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

        CONSTRAINT fk_book_publisher
        FOREIGN KEY (publisher_id)
        REFERENCES publisher (publisher_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
); 


CREATE TABLE music_cd(
    product_id VARCHAR(50) NOT NULL,
    label VARCHAR(200), 
    publication_date DATE, 

    CONSTRAINT pk_music_cd
        PRIMARY KEY (product_id),

    CONSTRAINT fk_music_cd_product
        FOREIGN KEY (product_id)
        REFERENCES product (product_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
); 

-- cd Liste von Titeln, die durch ihren Namen gegeben sind.
-- music_cd 1:n cd_title, da eine CD mehrere Titel haben kann, aber ein Titel nur zu einer CD gehört.
          --track numbers Wie hoch ist die durchschnittliche Anzahl von Liedern einer Musik-CD?

CREATE TABLE cd_title (
    product_id VARCHAR(50) NOT NULL,
    title_number INTEGER NOT NULL,
    title_name VARCHAR(300) NOT NULL,

    CONSTRAINT pk_cd_title
        PRIMARY KEY (product_id, title_number),

    CONSTRAINT fk_cd_title_music_cd
        FOREIGN KEY (product_id)
        REFERENCES music_cd (product_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT ck_cd_title_number
        CHECK (title_number > 0)
);

CREATE TABLE dvd(
    product_id VARCHAR(50) NOT NULL,
    format VARCHAR(100),
    runtime_minutes INTEGER,
    region_code INTEGER,
    CONSTRAINT ck_dvd_region CHECK(region_code BETWEEN 0 AND 8),   --dvd codes gehen von 1 bis 8 

    CONSTRAINT pk_dvd
        PRIMARY KEY (product_id),

      CONSTRAINT fk_dvd_product
        FOREIGN KEY (product_id)
        REFERENCES product (product_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT ck_dvd_runtime
        CHECK (runtime_minutes IS NULL OR runtime_minutes > 0) --falls unbekannt 
);

--customer
--customer_name ist in CSV als user geführt----
CREATE TABLE customer (
    customer_id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_name   VARCHAR(50) NOT NULL,

    CONSTRAINT pk_customer
        PRIMARY KEY (customer_id),
    CONSTRAINT uq_customer_name
        UNIQUE (customer_name),
    CONSTRAINT ck_customer_id
        CHECK (customer_id > 0)
);

--Filiale
CREATE TABLE store (
    store_id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    store_name    VARCHAR(300)  NOT NULL,
    street        VARCHAR(200),
    zip           VARCHAR(10),

    CONSTRAINT pk_store
        PRIMARY KEY (store_id),

    CONSTRAINT ck_store_id
        CHECK (store_id > 0)
);
-- Angebot
    CREATE TABLE offer (
    offer_id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id    VARCHAR(50)   NOT NULL,
    store_id      INTEGER       NOT NULL,
    price         DECIMAL(10,2),
    condition     VARCHAR(100),
    currency      VARCHAR(10),
-- sobald es für ein shop angeboten wird, ist es fest und kann nicht auf andere shops erweitert werden
-- künstlicher Schlüssel? Preis? 
    CONSTRAINT pk_offer
        PRIMARY KEY (offer_id),

    CONSTRAINT fk_offer_product
        FOREIGN KEY (product_id)
        REFERENCES product (product_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_offer_store
        FOREIGN KEY (store_id)
        REFERENCES store (store_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT chk_offer_price
        CHECK (price IS NULL OR price >= 0)
    );
-- price IS NOT NULL  => verfügbar
-- price IS NULL      => nicht verfügbar


-- Einkaufswagen
CREATE TABLE cart (
    cart_id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id     INTEGER NOT NULL,
    cart_time       TIMESTAMP NOT NULL,
    shipping_address VARCHAR(1000) NOT NULL,
    bank_account    VARCHAR(100) NOT NULL,

    CONSTRAINT pk_cart PRIMARY KEY (cart_id),
    CONSTRAINT fk_cart_customer 
        FOREIGN KEY (customer_id) 
        REFERENCES customer (customer_id)  
        ON UPDATE CASCADE 
        ON DELETE RESTRICT
);
--customer kann verschiedene Käufen; Lieferadressen; Kontodaten haben

CREATE TABLE cartposition (
    cart_id              INTEGER       NOT NULL,
    offer_id             INTEGER       NOT NULL,
    --product_id           VARCHAR(50)   NOT NULL,
    --store_id             INTEGER       NOT NULL,
    price_at_purchase    DECIMAL(10,2) NOT NULL,
    quantity             INTEGER       NOT NULL,


    CONSTRAINT pk_cartposition
        PRIMARY KEY (cart_id, offer_id),

    CONSTRAINT fk_cartposition_cart
        FOREIGN KEY (cart_id)
        REFERENCES cart (cart_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_cartposition_offer
        FOREIGN KEY (offer_id)
        REFERENCES offer (offer_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_cartposition_price
        CHECK (price_at_purchase >= 0),

    CONSTRAINT chk_cartposition_quantity
        CHECK (quantity > 0)
        
);


CREATE TABLE review (
    review_id       INTEGER GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    customer_id     INTEGER       NOT NULL,
    product_id      VARCHAR(50)   NOT NULL,
    rating          INTEGER       NOT NULL,
    helpful         INTEGER,
    summary         VARCHAR(500), 
    review_text     TEXT,
    review_date     DATE,
       

    CONSTRAINT pk_review
        PRIMARY KEY (review_id),

    CONSTRAINT fk_review_customer
        FOREIGN KEY (customer_id)
        REFERENCES customer (customer_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_review_product
        FOREIGN KEY (product_id)
        REFERENCES product (product_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT chk_review_rating
        CHECK (rating BETWEEN 1 AND 5)
);




-- was sucht man besonders häufig was nicht als PK gespeichert ist?
-- filtern nach produkttyp (dvd, cd, buch), filtern nach produktkategorie z.B. pop-cd, filtern nach 
-- bücher rausgegeben von xy verlag, oder cd küsntler,  filtern nach preis/angebot, filtern nach bewertung, verügbarkeit in einer filiale, 


CREATE INDEX idx_product_type ON product(product_type); --filtern nach produkttyp 
CREATE INDEX idx_review_rating ON review(rating); --filtern nach bewertung 
CREATE INDEX idx_offer_price ON offer(price); --filtern nach angebot/preis
CREATE INDEX idx_publisher_name ON publisher(publisher_name); --filtern nach verlagsnamen
CREATE INDEX idx_prod_cat_id ON product_category(category_id); --filtern nach kategorie
CREATE INDEX idx_category_parent ON category(parent_category_id); --schneller finden was ist unterkategorie, was oberk

CREATE INDEX idx_fk_cont_prod_cont   ON contributor_product(contributor_id);  -- wer zu welchen produkt beigetragen hat 
CREATE INDEX idx_fk_book_publisher   ON book(publisher_id); --welcher verlag welches buch published
CREATE INDEX idx_fk_offer_store      ON offer(store_id); --welche läden haben angebote
CREATE INDEX idx_fk_cart_customer    ON cart(customer_id); --welcher cart gehört zu welchem customer
CREATE INDEX idx_fk_review_customer  ON review(customer_id); -- welcher customer hat welche rezension hinterlassen
CREATE INDEX idx_fk_review_product   ON review(product_id); -- welches produkt hat welche rezension 

