# DATABASE CONNECTION Example 1.1. hibernate.properties for a c3p0 connection pool
#------------------------
hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc:postgresql://localhost:5432/mediastore
hibernate.connection.username=postgres
hibernate.connection.password=db19

# HIBERNATE Although SQL is relatively standardized, each database vendor uses a subset of supported syntax. 
# This is referred to as a dialect. Hibernate handles variations across these dialects through its
# org.hibernate.dialect.Dialect class and the various subclasses for each vendor dialect. 
#-----------------------------------------------------------
#hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect Wegen der Meldung aus der Ausgabe 
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.hbm2ddl.auto=validate
